### ISSUE TITLE
remove hashtag from url?

### ISSUE THREAD

**Issue by sprabowo** [dataformsjs/dataformsjs#1]
if i have root url / then /data for data page. in example, i need to move to #/data instead of /data. is it possible to remove it? i think spa can have pretty url without hashtag

**Comment by ConradSollitt** [comment]
Great Question Sigit,

I plan on adding it shortly (likely next month), although if you or someone else would like to help add it contributions are welcome and I would be happy to help out.

I had the issue documented in the [docs/to-do-list.txt](https://github.com/dataformsjs/dataformsjs/blob/master/docs/to-do-list.txt) file, however it's kind of buried in the docs.

For reference to get rid of the # hash URL the DOM History API (PushState, PopState) need to be used:
https://developer.mozilla.org/en-US/docs/Web/API/History_API

The affected files will be the main framework file:
[js/DataFormsJS.js](https://github.com/dataformsjs/dataformsjs/blob/master/js/DataFormsJS.js)

And a separate web component (possibly named: url-history-router) will be created based on the (url-hash-router) web component. Web Components for people not familiar with them are custom HTML elements that only work in modern browsers (no IE, Edge, or old Safari).
[js/web-components/url-hash-router.js](https://github.com/dataformsjs/dataformsjs/blob/master/js/web-components/url-hash-router.js)

**Comment by millette** [comment]
Plus, you'll need a fallback route if people are going to load those URLs directly.

**Comment by ConradSollitt** [comment]
Thanks Robin Millette,

Yes my current plans are to use hash routing for all examples on the site and then the main site will use the new History (pushstate) router. Both client side will need the fallback route and server-side (php for the main site) will need to handle each route.

I've created an early demo which I'll work on more next month. Although if someone would like to help out feel free to work on it and submit it as a pull request. The new file below [url-router.js] will go in the directory [js/web-components](https://github.com/dataformsjs/dataformsjs/tree/master/js/web-components)

Once the Web Component is completed then the main framework file will be updated. The JS file is in early development and includes several "TODO" statements. It doesn't yet handle fallback, and this specific demo only works when clicking on links as there is no server side code for it.

**Page for Testing**
https://dataformsjs.s3-us-west-1.amazonaws.com/tmp/url-router-test.htm

**New Web Component**
https://dataformsjs.s3-us-west-1.amazonaws.com/tmp/url-router.js

**Dependency File**
https://dataformsjs.s3-us-west-1.amazonaws.com/tmp/utils.js

**Comment by ConradSollitt** [comment]
Forgot to mention the above JS file:
https://dataformsjs.s3-us-west-1.amazonaws.com/tmp/url-router.js

Is based on the Web Component URL Hash Router:
https://github.com/dataformsjs/dataformsjs/blob/master/js/web-components/url-hash-router.js

They will be published in separate files to keep each web component as small as possible. To see the differences between the two use a Diff Tool. For Windows I would recommend WinMerge and for Mac type "filemerge" from Spotlight. There are plenty of online Diff sites to chose from as well.

Anyone recommend a diff tool for Linux or FreeBSD? For the past many years I've used both Linux and FreeBSD only from Command Line and haven't use Linux UI in years.

**Comment by ConradSollitt** [comment]
Changes for HTML5 History API support will likely be published to npm and the main site later this week. Currently they are in development and being tested at the following forks:

https://github.com/ConradSollitt/dataformsjs

https://github.com/ConradSollitt/website

**Comment by ConradSollitt** [comment]
Also for reference, this add change will add the following functions to the main framework file [DataFormsJS]:

app.routingMode();
app.routeChange();
app.pushStateClick(e);

By default Hash routing will be used and then to switch to HTML5 History API use the following:

<html data-routing-mode="history">

This code will affect all links on the page that start with "/" in the href, to turn off History API for matching links use the attribute [data-no-pushstate], this would not be common and would be used to redirect to another page on the server.

**Comment by ConradSollitt** [comment]
This is now available with the latest npm release 3.3.0 and the main site is using the new URL format.

Docs on how to use will be written and published to the quick reference page either later today or tomorrow.
